import { Inter } from "next/font/google";
import "./globals.css";
import { useDealerData } from "@/hooks/actions";
import Layout from "@/components/shared";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let data = await useDealerData();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout {...data}>{children}</Layout>
      </body>
    </html>
  );
}
