"use client";
export const DropDownTypes = {
  transmission: "transmission",
  bodyStyle: "bodystyles",
  years: "years",
  driveTrain: "driveTrain",
  conditions: "conditions",
  exteriorColors: "exteriorColors",
  salutations: "salutations",
  marital: "marital",
  homeStatus: "homeStatus",
  contractMethod: "contractMethod",
  months: "months",
  inventory_makes: "inventory_makes",
  inventory_minYear: "inventory_minYear",
  inventory_maxYear: "inventory_maxYear",
  inventory_model: "inventory_model",
  inventory_bodyStyle: "inventory_bodyStyle",
  inventory_Color: "inventory_Color",
  inventory_MinPrice: "inventory_MinPrice",
  inventory_MaxPrice: "inventory_MaxPrice",
  inventory_Transmission: "inventory_Transmission",
  inventory_FuelType: "inventory_FuelType",
  inventory_MinKm: "inventory_MinKm",
  inventory_MaxKm: "inventory_MaxKm",
  inventory_Engine: "inventory_Engine",
};
